### ISSUE TITLE
other port number?

### ISSUE THREAD

**Issue by victorclaessen** [JakobJFL/Hue-Browser-Controller#18]
Hi,

would it be possible to add an option to use a port number other than the default, like 8080?

Best regards,

Victor

**Comment by JakobJFL** [comment]
Hey, since I'm using the HUE API that uses HTTP it's not possible. Is there any particular reason you need to use a different Port? I can't do UDP over a browser because it requires hue API v2 if that is what you are looking for.

**Comment by victorclaessen** [comment]
I'm using [Home Assistant emulated HUE](https://www.home-assistant.io/integrations/emulated_hue/). My Home Assistant runs on port 80, so I've set the emulated hue to use port 8080.

**Comment by JakobJFL** [comment]
As I understand it the Hue controller will unfortunately not work with the emulated HUE because my controller uses Philips Hue API. You need to connect to a different API if there exists one for the emulated HUE which I don't know much about. You are always welcome to fork the repository and make your own implementation. :)
